#!/usr/bin/env bash

script_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
dry="0"

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	else
		filter="$1"
	fi
	shift # remove first argument from arguments list
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "-------------------- dev --------------------"
echo "scripts dir $script_dir"

copy_dir() {
	from=$script_dir/env/$1
	to=$2
	
	pushd $from > /dev/null # this changes current directory to $from and add it to stack. Redirect to /dev/null to keep output clean
	dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
	for dir in $dirs; do
		execute rm -rf $to/$dir
		execute cp -r $dir $to/$dir
	done
	popd > /dev/null # this removes cd from stack and changes directory to last used
}

copy_file() {
	from=$script_dir/env/$1
	to=$2
    file_name=$(basename $from)

    execute rm $to/$file_name
    execute cp $from $to/$file_name
}

copy_dir .config $XDG_CONFIG_HOME
copy_file .zshrc $HOME
copy_file .zsh_profile $HOME

log "-------------------- dev --------------------"
