#!/usr/bin/env bash

sudo apt update
echo "hello from neovim"
git clone -b "v0.10.3" "https://github.com/neovim/neovim.git" $HOME/personal/neovim
sudo apt-get install ninja-build gettext cmake unzip curl build-essential

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=Release
sudo make install

